[package]
name = "jsx-dom-expressions"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1"
swc_plugin = "*"

[dev-dependencies]
swc_ecma_transforms_testing = "0.83.0"
testing = "0.19.1"
swc_ecmascript = { version = "0.152.0", features = ["parser", "minifier", "utils", "visit", "transforms"] }
swc_common = { version = "0.17.25", features = ["concurrent", "sourcemap"] }
