[package]
name = "jsx-dom-expressions"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "*"
swc_plugin = "*"
swc_common = { version = "*", features = ["concurrent", "sourcemap"] }

[dev-dependencies]
swc_ecma_transforms_testing = "*"
testing = "*"
swc_ecmascript = { version = "*", features = ["parser", "minifier", "utils", "visit", "transforms"] }
