[package]
name = "jsx-dom-expressions"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1"
swc_plugin = "0.68"
swc_common = { version = "0.20", features = ["concurrent", "sourcemap"] }

[dev-dependencies]
swc_ecma_transforms_testing = "0.95"
testing = "0.22"
swc_ecmascript = { version = "0.172", features = ["parser", "minifier", "utils", "visit", "transforms"] }
